### ISSUE TITLE
coze是使用的GPT4还是3.5呢？

### ISSUE THREAD

**Issue by snailg** [bincooo/chatgpt-adapter#15]
问了相同的问题，chatgpt-adapter代理回答的结果像3.5的答案。
![image](https://github.com/bincooo/chatgpt-adapter/assets/5671609/d8a8ade8-f4f6-4fc4-be39-eddbd82fe9d1)

我用网页测试的结果还算可以。
![image](https://github.com/bincooo/chatgpt-adapter/assets/5671609/2fa933fb-e993-45ea-a246-68107ce852b0)

**Comment by bincooo** [comment]
https://github.com/bincooo/chatgpt-adapter/issues/12

和这个兄弟的一样，可能是签名里有一些字段被识别出来了。目前修复不了

**Comment by bincooo** [comment]
<img width="788" alt="Screenshot 2024-05-24 at 02 56 29" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/d38a9d25-aa33-428e-87dc-523aa2bf26da">

更新了签名，看起来正常了
