### ISSUE TITLE
新版的cohere忽然变得很蠢

### ISSUE THREAD

**Issue by normana234** [bincooo/chatgpt-adapter#16]
表现为不听人说话，感觉就像把温度调到比最高还高的那种。
更到最新版，没有解决。
然后用同一个API测试之前部署的有几个星期没更新的版本，智商正常。
应该就是最近几次更新的问题。

**Comment by bincooo** [comment]
那你在输入时加个<notebook />试试，新版和过去的版本变化的貌似就只有 以前默认使用generate模式，现在是chat模式。
有截图吗？我测试一下

**Comment by om8mo** [comment]
> 那你在输入时加个试试，新版和过去的版本变化的貌似就只有 以前默认使用generate模式，现在是chat模式。 有截图吗？我测试一下`<notebook />`

测试了，加上这个标签后就正常了。

**Comment by normana234** [comment]
> 那你在输入时加个`<notebook />`试试，新版和过去的版本变化的貌似就只有 以前默认使用generate模式，现在是chat模式。 有截图吗？我测试一下

@bincooo  试了这个标签，有效，应该是这个原因
![1](https://github.com/bincooo/chatgpt-adapter/assets/155615225/52b2e0db-071a-479c-92f8-5ca98f32b4a7)
![2](https://github.com/bincooo/chatgpt-adapter/assets/155615225/1668371b-c06c-4438-b782-ffbb14fb61a0)
