### ISSUE TITLE
Sending an image

### ISSUE THREAD

**Issue by devanenWl** [bincooo/chatgpt-adapter#19]
Hi, thanks for creating such a good project
Coze has updated gpt-4o
So could you please add support sending image to coze ? Thank you very much
<img width="1440" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/8446682/83899cb2-f16f-4778-b8bb-325709157801">

**Comment by bincooo** [comment]
maybe can do it, but it's not a gpt4o attachment recognition image, it's a gpt4v plugin parsing the url.
It takes time.

**Comment by devanenWl** [comment]
<img width="769" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/8446682/da996abd-c7de-4902-8d22-85126d538a09">
I have tried but it still not works. Could you please check it again please ? I'm using Lobe-chat

**Comment by bincooo** [comment]
i'm testing pass
<img width="1473" alt="Screenshot 2024-06-01 at 00 53 50" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/67f054ed-eca5-47f8-a41d-6143df0497b9">

Make sure your program is up to date with the latest commit, and if you use custom `coze` make sure you add the gpt4v plugin
<img width="455" alt="Screenshot 2024-06-01 at 00 59 09" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/87244ebc-58bf-4b30-80d0-98e17805e06d">

**Comment by devanenWl** [comment]
Hi, I have tried once again by using default model ```coze```
But it still not works
I have updated my program.
<img width="768" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/8446682/93a7ff56-353e-4057-b2ad-b0e9625fda0b">

**Comment by bincooo** [comment]
It's incredible! I can't guess what the problem is...

I use it is normal recognition. This is the service demo I posted on huggingface, You can try it here:

[jump](https://complete-mmx-chatgpt-adapter.hf.space)

```curl
curl -i -X POST \
   -H "Content-Type:application/json" \
   -H "Authorization:{YOUR_COOKIES}" \
   -d \
'{
  "messages": [
    {
      "content": "<|user|>\ndescribe this\n\n*image*:  https://complete-mmx-easy-images.hf.space/images/6e2e391472c021bb483a8aa4fd250fa2.jpg\n----<|end|>\n<|assistant|>",
      "role": "user"
    }
  ],
  "tools": [
  ],
  "model": "coze",
  "stream": false,
  "tool_choice": "auto"
}' \
 'https://complete-mmx-chatgpt-adapter.hf.space/proxies/v1/chat/completions'
```

**Comment by GeekWorkCode** [comment]
Hello! Does this support the attachment function of gpt-4o and claude 3 sonnet? I think the request example is only the way to send it in plain text.

**Comment by cennne** [comment]
<img width="468" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/34563979/bcacdf0e-1c88-406b-baed-fd11a6e70ded">
Seems like it because of this

**Comment by devanenWl** [comment]
Plugin:
<img width="878" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/8446682/a72995ac-fe51-41b1-a195-7e7c567d93c8">
GPT-4o
<img width="458" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/8446682/b87814a0-a1a2-41dc-8153-4ffb566bd3db">

This is the difference between using gpt-4o and GPT4V plugin @bincooo 
Can you please update this ?

**Comment by bincooo** [comment]
Unofficial interfaces cannot be completely restored to the original function

**Comment by devanenWl** [comment]
Okay thank you by the way.
