### ISSUE TITLE
请问，我按照Readme中的方法启动之后，如何配置Bing或者Claude呢？

### ISSUE THREAD

**Issue by jgbrblmd** [bincooo/chatgpt-adapter#2]
有没有文档或着在哪个网页里有使用实例说明？谢谢！
启动后显示：

```
./exec --port 8081 --proxy http://192.168.1.16:8119
🎉🎉🎉 Network success! 🎉🎉🎉
INFO[0008] Start by http://127.0.0.1:8081/v1
[GIN] 2023/10/16 - 08:54:21 | 200 |      31.888µs |       127.0.0.1 | GET      "/"
```

然后访问这个地址http://127.0.0.1:8081/v1，网页显示：

```
Start by http[s]://127.0.0.1:8081/v1

version: v1.0.12
project: github.com/bincooo/AutoAI
```

如何配置new bing或者claude2呢？
能不能给一个有例子的.env.sample文件呢？

**Comment by jgbrblmd** [comment]
我在exmples里找到一些main.go，但是因为不会go语言，不知到如何启动，以及这些文件和exec启动的服务的关系。

**Comment by jgbrblmd** [comment]
现在我在.env中配置了bing的token,
启动时显示：当前IP地址: 207.228.xxx.xxx, 美国内华达
使用ChatGPT Next调用BingAI模型，显示404错误。
服务器端显示两行：

[GIN] 2023/10/16 - 10:24:40 | 200 |     184.896µs |       127.0.0.1 | OPTIONS  "/v1/v1/chat/completions"
[GIN] 2023/10/16 - 10:24:41 | 404 |       3.512µs |       127.0.0.1 | POST     "/v1/v1/chat/completions"

一个是200的状态码，一个是404

**Comment by bincooo** [comment]
这个程序可以理解为claude/bing 转openai接口，openai如何调用，它就是如何调用

**Comment by jgbrblmd** [comment]
> 这个程序可以理解为claude/bing 转openai接口，openai如何调用，它就是如何调用 只不过`Authorization`的值更换成对应的cookie（token）参数 

谢谢回复！我已经按照这个思路配置通了new bing，但是claude无论是通过slack还是通过web都不通，而且填充废料注释掉也不行，我再研究一下，如果还是不行再来更新。

谢谢回复！
