### ISSUE TITLE
指定coze bot的问题

### ISSUE THREAD

**Issue by longlegmax** [bincooo/chatgpt-adapter#20]
支持指定bot模型：
格式 -> coze/botId-version-scene; 例子 -> coze/7353052833752694791-1712016747307-2

请问version的值从哪里去寻找？我用f12查看，botid和scene都能方便的找到。

**Comment by bincooo** [comment]
进入发布后的bot页面，发送一条消息。在开发者工具网络里，找到
https://www.coze.com/api/conversation/chat?xxxxx
<img width="1897" alt="Screenshot 2024-05-28 at 17 27 11" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/99b0524c-7cc9-49ab-9722-aa9800b2c288">

**Comment by longlegmax** [comment]
非常感谢，已解决
