### ISSUE TITLE
作者能否直接提供docker镜像部署

### ISSUE THREAD

**Issue by linkiofo** [bincooo/chatgpt-adapter#21]
作者能否直接提供docker镜像部署

**Comment by linkiofo** [comment]
是的，发布到ghcr.io或者docker.io都行

**Comment by linkiofo** [comment]
@bincooo 感谢你开发这么好项目！我还有问题想请教下这个项目能对接oneapi项目使用吗？

**Comment by bincooo** [comment]
能

**Comment by RockChinQ** [comment]
我看wf写了判断分支名并构建latest的逻辑，应该是要在每次push的时候就构建一次latest镜像吧？可是我拉latest镜像提示没有这个tag，是否是没能成功在每次push时构建？

**Comment by bincooo** [comment]
不是，需要我创建release才会触发

**Comment by RockChinQ** [comment]
好的，所以是会在release的时候推送一个`tag=版本号`和`tag=latest`的镜像是吗？但是我[这里](https://github.com/users/bincooo/packages/container/chatgpt-adapter/versions?filters%5Bversion_type%5D=tagged)并没有看到有tag为latest的镜像？

**Comment by bincooo** [comment]
> 好的，所以是会在release的时候推送一个`tag=版本号`和`tag=latest`的镜像是吗？但是我[这里](https://github.com/users/bincooo/packages/container/chatgpt-adapter/versions?filters%5Bversion_type%5D=tagged)并没有看到有tag为latest的镜像？

没有latest

**Comment by RockChinQ** [comment]
可以麻烦加一下吗？打算贡献文档加一下docker方式的文档，但每个版本都要改命令比较麻烦

**Comment by bincooo** [comment]
> 可以麻烦加一下吗？打算贡献文档加一下docker方式的文档，但每个版本都要改命令比较麻烦

可以
