### ISSUE TITLE
coze报No permission错误

### ISSUE THREAD

**Issue by yinmao** [bincooo/chatgpt-adapter#23]
cookie为浏览器正常请求的cookie；
报错：{"error":{"message":"{\"code\":700012054,\"msg\":\"No permission to access, please refresh the current page and try again.\"}"}}

**Comment by devanenWl** [comment]
you need to publish your coze bot first

**Comment by jonntd** [comment]
解决了么老哥

**Comment by yinmao** [comment]
使用最新版本，配置botId和Version后可解决
