### ISSUE TITLE
能否示例：如何让没有toolCall能力的AI也能执行任务？

### ISSUE THREAD

**Issue by bingjiw** [bincooo/chatgpt-adapter#25]
能否示例：如何让没有toolCall能力的AI也能执行任务？

比如 通义千问 qwen-max, qwen-turbo等API现在不支持 搜索、天气、问时间 等，要如何结合本项目来解决这个问题呢？

如何实现：
当用户问 “搜索、天气、问时间 ” 时如何调用toolCall得到结果。
当用户问 “其他问题” 时仍交由通义千问 qwen-max, qwen-turbo等API来给用户回答。

谢谢。

**Comment by bincooo** [comment]
本项目目前只接入网页newbing、claude、coze、lmsys，暂不支持其它ai

**Comment by bincooo** [comment]
不要重复开启issue，这个关闭了 #27
