### ISSUE TITLE
太好了：添加v1接口转发，实现上游llm toolCall拓展。上游是指什么？

### ISSUE THREAD

**Issue by bingjiw** [bincooo/chatgpt-adapter#27]
太好了，看到作者有：添加v1接口转发，实现上游llm toolCall拓展。

请问上游是指什么？

用户 -> one-api -> chatgpt-adapter -> LLM models

是否图中的  one-api 是上游？

**Comment by bincooo** [comment]
所有支持`chatgpt` `/v1/chat/completions` 接口的服务
