### ISSUE TITLE
Error when the message/chat is too long

### ISSUE THREAD

**Issue by cennne** [bincooo/chatgpt-adapter#28]
<img width="582" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/34563979/66de8ea4-edbe-4721-919e-0773a84e5150">

[https://stackoverflow.com/questions/19917401/error-request-entity-too-large](url)
I think we should increase the limit

**Comment by bincooo** [comment]
I missed that point, thanks for reminding me.

**Comment by bincooo** [comment]
It has been updated to 100m and should have taken effect at this point

**Comment by cennne** [comment]
I have tried again and it still have that error, did you push the commit ?

**Comment by bincooo** [comment]
No push needed. What about now?

**Comment by devanenWl** [comment]
Okay it's working. Thank you

**Comment by cennne** [comment]
Works right now. Thank you
