### ISSUE TITLE
有空研究下coze.cn吗?

### ISSUE THREAD

**Issue by zhepamagod** [bincooo/chatgpt-adapter#30]
我能获取coze.cn请求时的a_bogus了..
可是请求还是失败了...

**Comment by bincooo** [comment]
国内的豆包ai看起来没有多少出彩的地方，注册渠道也只有一个，所以没想去搞

**Comment by zhepamagod** [comment]
感谢回复..已经解决了.
国内的不只有豆包,
还有qwenmax,还有moonshot..这两个还行的..
其他的还有minimax
