### ISSUE TITLE
报错了coze No permission to access, please refresh the current page and try again.

### ISSUE THREAD

**Issue by jonntd** [bincooo/chatgpt-adapter#31]
code=700012054 msg=No permission to access, please refresh the current page and try again.

**Comment by bincooo** [comment]
是不是重新发布了coze的bot但是verison没更新

**Comment by bincooo** [comment]
额，诸位拿来干了什么吗。
Bot被封了。。。

<img width="1070" alt="Screenshot 2024-06-07 at 06 48 53" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/f8beb98f-a468-48f8-8ffe-68df70fcaf44">

我改一下配置，让你们用自己配置的吧😮‍💨

**Comment by jonntd** [comment]
据说coze发布机器人不让带 gpt ai 啥的名字了

**Comment by bincooo** [comment]
进入coze.com, 选择一个bot
<img width="977" alt="Screenshot 2024-06-07 at 10 18 08" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/dd4ef331-b29f-401b-bf64-43edab4d196b">

F12 进入开发者面板，在bot输入框中随意发言，最后在开发者面板中获取

<img width="996" alt="Screenshot 2024-06-07 at 10 21 29" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/9bc04f8a-fcb6-4e7a-905f-a57919a5dd99">
