### ISSUE TITLE
配置了custom llm 之后，启用 toolcall崩溃

### ISSUE THREAD

**Issue by a8851625** [bincooo/chatgpt-adapter#32]
server-1  | 2024-06-06 06:30:28 <internal/plugin/llm> v1/message.go:88 | [INFO] waitResponse ...
server-1  | 2024-06-06 06:30:28 <internal> gin.handler/basic.go:101 | [ERRO] response error: runtime error: invalid memory address or nil pointer dereference
server-1  | 2024-06-06 06:30:28 <internal> gin.handler/basic.go:95 | [INFO] 
server-1  | ------ END REQUEST 5a85c035-5c49-4ebc-812d-470740e879f6 ---------
server-1  | [GIN] 2024/06/06 - 06:30:28 | 500 |   4.02276008s |   192.168.31.51 | POST     "/v1/chat/completions"

后端是 用 one api的 openai代理白嫖的千问 https://github.com/LLM-Red-Team/qwen-free-api

**Comment by bincooo** [comment]
已更新
