### ISSUE TITLE
arm docker 运行报错

### ISSUE THREAD

**Issue by jonntd** [bincooo/chatgpt-adapter#33]
./server: line 0: syntax error: unexpected "|"

**Comment by bincooo** [comment]
没有做arm支持的编译

**Comment by jonntd** [comment]
我自己编译的

**Comment by jonntd** [comment]
配置里写模型运行报 {"error":{"message":"fetch bot info failed: permissionless operation"}}
coze:
 8k:
    botId: 7377250993274748936
    version: 1717746535974
    scene: 2
 128k:
    botId: 7377250993274748936
    version: 1717746535974
    scene: 2

curl 里填模型不报错
  "model": "coze/7377250993274748936-1717746535974-2",

**Comment by bincooo** [comment]
非开发者面板的需要把isO改为false

**Comment by jonntd** [comment]
coze:
  8k:
    botId: 7377250993274748936
    version: 1717746535974
    scene: 2
    isO: false
    
{'error': {'message': 'fetch bot info failed: permissionless operation'}}
改了也不行

**Comment by bincooo** [comment]
<img width="784" alt="Screenshot 2024-06-07 at 16 50 03" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/f0ee823c-0e72-4aad-b629-108c8093207a">
<img width="1837" alt="Screenshot 2024-06-07 at 16 50 21" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/6e38f077-7d16-4357-88f8-ec0ac4202f39">


无法重现，你修改配置后有重启吗
