### ISSUE TITLE
arm64  ghcr.io 那个是错误的吧

### ISSUE THREAD

**Issue by jonntd** [bincooo/chatgpt-adapter#35]

**Comment by bincooo** [comment]
没试过，你可以试试。携带push号
docker pull ghcr.io/bincooo/chatgpt-adapter:latest@sha256:17d74c481edcfea7b9ad8b0fe121a8c068d73f5d20f7a076f113dde8d953945f


裸机测试在 `aidlux` 是能跑

**Comment by jonntd** [comment]
我甲骨文arm 测试 跑不起来 直接报错 ./server: line 1: syntax error: unexpected word (expecting ")")

**Comment by bincooo** [comment]
[server-arm64.zip](https://github.com/user-attachments/files/15782707/server-arm64.zip)
试试直接运行

**Comment by bincooo** [comment]
这种错误信息，一般就是平台编译的问题。
你是使用我提供的镜像吗

**Comment by jonntd** [comment]
docker pull ghcr.io/bincooo/chatgpt-adapter:latest@sha256:17d74c481edcfea7b9ad8b0fe121a8c068d73f5d20f7a076f113dde8d953945f
用的这个 
之前你发布过  ghcr.io/bincooo/chatgpt-adapte-arm64 那个能用，后来给删除了吗

**Comment by jonntd** [comment]
> [server-arm64.zip](https://github.com/user-attachments/files/15782707/server-arm64.zip) 试试直接运行

goroutine 1 [running]:
github.com/bincooo/chatgpt-adapter/internal/plugin/llm/coze.init.0.func1()
        github.com/bincooo/chatgpt-adapter/internal/plugin/llm/coze/adapter.go:59 +0x4f8
github.com/bincooo/chatgpt-adapter/internal/common.InitCommon(...)
        github.com/bincooo/chatgpt-adapter/internal/common/com.go:16
main.glob..func1(0x40001f8700?, {0xbf8f24?, 0x7?, 0xbef535?})
        ./command.go:37 +0xf4
github.com/spf13/cobra.(*Command).execute(0x17fc120, {0x400003a0b0, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x17fc120)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        ./command.go:50 +0x14c

**Comment by bincooo** [comment]
配置文件coze添加 
isW: false

<img width="344" alt="Screenshot 2024-06-11 at 14 21 40" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/91f1fa36-cf54-45df-a1c1-de319f2437e8">

**Comment by bincooo** [comment]
> docker pull ghcr.io/bincooo/chatgpt-adapter:latest@sha256:17d74c481edcfea7b9ad8b0fe121a8c068d73f5d20f7a076f113dde8d953945f 用的这个 之前你发布过 ghcr.io/bincooo/chatgpt-adapte-arm64 那个能用，后来给删除了吗

那就分开发布吧，本想着放到一起。看来不行
