### ISSUE TITLE
webSdk模式 报错 Login verification is invalid

### ISSUE THREAD

**Issue by jonntd** [bincooo/chatgpt-adapter#37]
Connection: keep-alive
Content-Length: 119
Content-Type: application/json
User-Agent: python-requests/2.29.0
2024-06-12 07:07:20 <github.com/bincooo/chatgpt-adapter/internal/plugin/llm> coze/adapter.go:307 | [INFO] using custom coze options: botId = 737950xxxxxx, version = xxx, scene = 1000
2024-06-12 07:07:20 <github.com/bincooo> coze-api@v1.0.2-0.20240606225815-85aeed60c707/chat.go:68 | [INFO] {"maigc":538051346,"version":1,"dataType":8}
2024-06-12 07:07:20 <github.com/bincooo/chatgpt-adapter/internal/plugin/llm> coze/adapter.go:214 | [ERRO] Login verification is invalid

**Comment by bincooo** [comment]
model 是否为 `-w` 结尾？
例：`coze/73775577xxxxxxx-xxx-1000-w`

**Comment by jonntd** [comment]
'model': 'coze/73795034*****-xxx-1000-w'

**Comment by bincooo** [comment]
无法重现，可否提供请求参数以便调试？

**Comment by jonntd** [comment]
#coze:
#  8k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  128k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  images:
#    botId: 114514
#    version: 9527
#    scene: 2
把这个注销就能用了

**Comment by jonntd** [comment]
> 无法重现，可否提供请求参数以便调试？

coze:
 8k:
   botId: 114514
   version: 9527
   scene: 2
   isW: false
 128k:
   botId: 114514
   version: 9527
   scene: 2
   isW: false

现在开启这个就报错，不开启  
'model': 'coze/73795034*****-xxx-1000-w'
这样可以用

**Comment by bincooo** [comment]
请尝试直接在控制台执行请求：
```shell
curl -i -X POST \
   -H "Content-Type:application/json" \
   -d \
'{
  "messages": [
    {
      "content": "你好",
      "role": "user"
    }
  ],
  "tools": [
    {
      "function": {
        "description": "获取用户当前时区的时间。",
        "name": "AXdUGbeDyuLV",
        "parameters": {
          "properties": {},
          "required": [],
          "type": "object"
        }
      },
      "type": "function"
    }
  ],
  "model": "coze/7377557797556764690-xxx-1000-w",
  "max_tokens": 0,
  "stop_sequences": null,
  "temperature": 0,
  "topK": 0,
  "topP": 0,
  "stream": true,
  "tool_choice": "auto"}' \
 'http://127.0.0.1:8081/v1/chat/completions'
```

**Comment by jonntd** [comment]
> 无法重现，可否提供请求参数以便调试？
C:\Users\Admin\Downloads\chatgpt-adapter_0.0.0_windows_amd64>chatgpt-adapter.exe
panic: interface conversion: interface {} is nil, not bool

goroutine 1 [running]:
github.com/bincooo/chatgpt-adapter/internal/plugin/llm/coze.init.0.func1()
        /home/runner/work/chatgpt-adapter/chatgpt-adapter/internal/plugin/llm/coze/adapter.go:59 +0x505
github.com/bincooo/chatgpt-adapter/internal/common.InitCommon(...)
        /home/runner/work/chatgpt-adapter/chatgpt-adapter/internal/common/com.go:16
main.init.func1(0xc000136100?, {0x1415382?, 0x7?, 0x140b8a0?})
        /home/runner/work/chatgpt-adapter/chatgpt-adapter/cmd/command.go:37 +0xe8
github.com/spf13/cobra.(*Command).execute(0x20937a0, {0xc00004c180, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x20937a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/chatgpt-adapter/chatgpt-adapter/cmd/command.go:50 +0x145

**Comment by jonntd** [comment]
isW: false
   isO: false

找到原因了，配置文件用的以前的 isO 现在改成 isW了

**Comment by bincooo** [comment]
解决了么？若无其他问题把issue关闭吧
