### ISSUE TITLE
请问要如何继续上一次的会话

### ISSUE THREAD

**Issue by xiewenqian** [bincooo/chatgpt-adapter#4]
我在使用bingAI的时候，需要从上一次会话的末尾继续，请问要如何调用接口

**Comment by xiewenqian** [comment]
@bincooo

**Comment by bincooo** [comment]
`types.ConversationContext`的`Chain`中有个`cahce`执行器，可以缓存每次对话。
如果你想手动处理历史消息，可以自行调用`store.CacheMessages()`覆盖：
https://github.com/bincooo/chatgpt-adapter/blob/03a04e55978e3ed6b6f1e516b1b890367f1c10a4/store/message.go#L16
https://github.com/bincooo/chatgpt-adapter/blob/d727e8bff870ebdcb2e5fdf8c2faf035a91d8a96/examples/gemini/main.go#L41

**Comment by xiewenqian** [comment]
可能我表述的不是很清楚，我是想咨询是否支持下面这样操作
// 创建对话
const conversation = await openai.conversations.create({});
// 保存对话ID以便后续使用
const conversationId = conversation.id;
// 使用对话ID发送消息并获取响应
const response = await openai.conversations.message({
  conversationId: conversationId,
  message: 'Hello, World!'
});
