### ISSUE TITLE
bing的三个模型区别是什么？

### ISSUE THREAD

**Issue by normana234** [bincooo/chatgpt-adapter#40]
从命名法看，bing-online是联网，bing-vision是视觉模型。
主要是测试时发现，bing(无后缀)也是联网无视觉的，和bing-online的区别感觉不出来。

**Comment by bincooo** [comment]
哦，缺了参数，我后面补上

**Comment by normana234** [comment]
@bincooo bing确实不联网了，现在变成bing-vision没法识图(更新前可以的)。

**Comment by bincooo** [comment]
没出现这种情况
<img width="1054" alt="Screenshot 2024-06-18 at 17 00 48" src="https://github.com/bincooo/chatgpt-adapter/assets/36452456/659023e7-61f0-43d7-be2e-8ab4377704b7">

**Comment by om8mo** [comment]
@bincooo 刚试了下确实可以了，打扰了。
