### ISSUE TITLE
tcp连接占用时间太长导致请求量大时进程文件打开数过多报错

### ISSUE THREAD

**Issue by zeng-rr** [bincooo/chatgpt-adapter#41]
目前测试看到的tcp连接（服务端发起的请求）在客户端请求结束后还会生存10分钟左右才被释放，能不能在请求结束后及时关闭连接释放资源，并且可以接收一个请求超时时间参数来设置请求超时，避免连接长时间占用

**Comment by bincooo** [comment]
你说的是 ESTABLISHED 空闲连接的释放周期过长吗？还是什么

**Comment by zeng-rr** [comment]
> 你说的是 ESTABLISHED 空闲连接的释放周期过长吗？还是什么

是的，客户端的请求已经结束了，服务端发起的请求建立的连接还会保持很长一段时间的ESTABLISHED，这些连接既没有释放也没有被复用，导致有新的请求进来连接数就会一直增长

**Comment by zeng-rr** [comment]
已解决，感谢作者帮助！
