### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by devanenWl** [bincooo/chatgpt-adapter#48]
<img width="384" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/8446682/f4594b28-afcb-4e4c-811b-5393e4fc72ea">
<img width="1123" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/8446682/1430afda-b5ad-48c4-86cb-313d15efec75">

After update today, something just went wrong.
It was interrupted.

**Comment by devanenWl** [comment]
<img width="1129" alt="image" src="https://github.com/bincooo/chatgpt-adapter/assets/8446682/261a3915-de2d-4d96-9c7b-aba70ad2c831">
I have rolled back to previous version, it works normally

**Comment by bincooo** [comment]
fix

**Comment by devanenWl** [comment]
Can you tell me what commit did you push to fix this ? I want to know why it causes this error. Thank you

**Comment by bincooo** [comment]
[fix commit](https://github.com/bincooo/chatgpt-adapter/commit/c7e3e3f58413b417244bba28fce9669475cd7f36)
