### ISSUE TITLE
能不能加上bing的处理啊，返回的是几个几个的单词，需要手动拼接，可以把拼接这一步加进去吗？

### ISSUE THREAD

**Issue by leioukupo** [bincooo/chatgpt-adapter#52]
![image](https://github.com/bincooo/chatgpt-adapter/assets/60430874/7cac2925-3cc9-4282-95d2-b61a62bc3db8)
返回很多data
能不能自动拼接到一起

**Comment by bincooo** [comment]
你把 stream 改为false试试？

**Comment by leioukupo** [comment]
> 你把 stream 改为false试试？

可以了，没注意到
还有个问题，怎么鉴权？没看到请求的时候有密钥啥的，要是别人知道了ip，不也能使用了，我部署在公网服务器

**Comment by bincooo** [comment]
没有鉴权，你想鉴权的话就挂到oneapi服务里用它鉴权

**Comment by leioukupo** [comment]
> 没有鉴权，你想鉴权的话就挂到oneapi服务里用它鉴权

oneapi选自定义渠道吗？？密钥是不是自己设定？？模型名字怎么填？

**Comment by leioukupo** [comment]
弄好了
