### ISSUE TITLE
Got 3.5-turbo instead of 4

### ISSUE THREAD

**Issue by devanenWl** [bincooo/chatgpt-adapter#58]
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/debfd90c-914d-4d20-9632-21d63e2c06d2">

Something went wrong.

**Comment by bincooo** [comment]
It was repaired,
This should be due to an error caused by my previous commit changes to userAgent.

**Comment by devanenWl** [comment]
I still got the same after updating the repo
It will works fine with some first accounts
But after few accounts, it only uses 3.5 turbo

**Comment by devanenWl** [comment]
https://github.com/bincooo/coze-api/issues/7
I think it's the same like this

**Comment by bincooo** [comment]
<img width="1589" alt="Screenshot 2024-07-14 at 19 40 16" src="https://github.com/user-attachments/assets/eed7b398-a1c5-4c9a-b902-6418e98e7477">
<img width="1261" alt="Screenshot 2024-07-14 at 19 40 59" src="https://github.com/user-attachments/assets/7cf05436-4a9a-4fbd-9d49-db84e7fea174">

It's normal for me to see it here.
`chatgpt-adapter` drops the session after each session, so there should be no `msToken` reuse.
I'll take some time to check.

**Comment by devanenWl** [comment]
You should send at least 10 accounts to reproduce this, on the same IP

**Comment by bincooo** [comment]
I created 10 cookies, but they don't seem to reproduce your problem...

<img width="399" alt="Screenshot 2024-07-14 at 22 53 05" src="https://github.com/user-attachments/assets/b7be83db-7627-46a1-9000-b3b8fa3b8b28"> <br/>

<img width="399" alt="Screenshot 2024-07-14 at 22 59 06" src="https://github.com/user-attachments/assets/1463691b-a35e-44d6-a072-c7c93f09eec3">


Can you execute this script on your machine and let me know the result?
https://github.com/bincooo/coze-api/blob/454361cb01d3c1439a54eed2445b45eb976bf2df/chat_test.go#L24

**Comment by devanenWl** [comment]
Do you have telegram or email ? I will send you the api for easier to debug. I have tested the script and it works fine but when I use 
https://github.com/devanenWl/chatgpt-adapter/tree/merge_2 this one, 
it returns chatgpt 3.5. Basically I just add mongodb for handling multi accounts

**Comment by bincooo** [comment]
Well, my email: bingco.zn@gmail.com

**Comment by devanenWl** [comment]
I have sent you an email, please check it. Thank you

**Comment by bincooo** [comment]
I received the information you provided.
A few requests were tried, and it seemed normal. How can I make this mistake happen?

**Comment by devanenWl** [comment]
[Video](https://streamable.com/bok988)
Watch this

**Comment by bincooo** [comment]
I reproduced this error, and while running continuously, it returned to normal when I tried to switch ip halfway through.
It's more like coze detected abnormal traffic, what do you think?

**Comment by bincooo** [comment]
<img width="867" alt="Screenshot 2024-07-15 at 12 32 45" src="https://github.com/user-attachments/assets/9470de0a-19be-483c-be82-faab1b8339c1">
locking...

**Comment by bincooo** [comment]
Even conversations directly on the page are switched to gpt35. I hope it's not permanent...

**Comment by devanenWl** [comment]
Yeah, I think if over 10 accounts are used on the same IP, it will cause this issue

**Comment by bincooo** [comment]
In that case, either build an ip pool or abandon the pattern.
websdk should be the last mode available, but there is a 100 credit limit, although it can be reset by deleting an account. But I guess `coze` will fix it later

**Comment by devanenWl** [comment]
I have rechecked again.

This is when the bot send requests
<img width="372" alt="image" src="https://github.com/user-attachments/assets/ed601639-297c-4d03-8fa4-7ed624234987">

This is when I come to browser and press retry:
<img width="378" alt="image" src="https://github.com/user-attachments/assets/b75c40c2-0199-4fc5-8501-753af6531a67">

I think that Coze have checked if the browser is real or not

**Comment by devanenWl** [comment]
Check this out: [Video](https://streamable.com/mzvtfm)

**Comment by bincooo** [comment]
Are ip addresses consistent? Mine is still gpt3.

[Video](https://streamable.com/s7vdox)

**Comment by devanenWl** [comment]
Yes, the IP is consistent

**Comment by devanenWl** [comment]
I think if the accounts is `flagged` because of spam, even on browser, it won't be able to use GPT-4o
But if this is the first/second time that the account is used (even the IP is `flagged`), it will works fine on browsers
Watch this: [Video](https://streamable.com/kuysvq)

**Comment by bincooo** [comment]
My email is manually created by gmail, and I can't guess its determination mechanism

**Comment by devanenWl** [comment]
Can you create a new account and test it or delete and recreate ?

**Comment by bincooo** [comment]
The site denied access

<img width="139" alt="Screenshot 2024-07-15 at 14 34 59" src="https://github.com/user-attachments/assets/867b7ad1-0de6-48cb-b0b9-673cffce0e33">

**Comment by bincooo** [comment]
Please pay attention to the mailbox.

**Comment by devanenWl** [comment]
Okay, btw thank you. I think we should close this. Perhaps delete it.
