### ISSUE TITLE
希望能为bing加上Creative，Balanced，Precise三种模式的切换参数

### ISSUE THREAD

**Issue by reccea** [bincooo/chatgpt-adapter#59]
能手动更改bing的Creative，Balanced，Precise三种模式最好，能用传不同参数来实现吗？

**Comment by bincooo** [comment]
https://github.com/bincooo/edge-api/blob/d92610338ccb6ecb12e9e27d5f395ed9114101b2/chat.go#L560
你可以配置temperature来选择这三个模式

**Comment by reccea** [comment]
> https://github.com/bincooo/edge-api/blob/d92610338ccb6ecb12e9e27d5f395ed9114101b2/chat.go#L560 你可以配置temperature来选择这三个模式

你引用这个是edge-api的，chatgpt-adapter也一样吗？在post数据时加上一个temperature值吗？当前默认不设置时是不是0.9？

**Comment by bincooo** [comment]
默认为0

**Comment by reccea** [comment]
> 默认为0

发现一个问题，bing和bing-online的智商好像有点不同，拿经典的测试gpt3.5和gpt4区别的问题分别问bing和bing-online，“西红柿炒钢丝球这道菜怎么做?”，bing能和gpt4一样，知道这是个不存在的问题。而bing-online和gpt3.5一样，正儿八经给出荒谬的食谱。
但测试鲁迅和周树人之类问题，bing和bing-online又正常。

**Comment by bincooo** [comment]
现在的bingAI就是一坨屎，官网联网的bingAI更是屎中的屎。
<img width="961" alt="Screenshot 2024-07-17 at 16 20 54" src="https://github.com/user-attachments/assets/ca5a4549-65ea-4fa3-8c0c-d02c1a71610f">

没什么好说的，我都懒得维护它了

**Comment by bincooo** [comment]
而且现在页面上没有三模式了，所以我也不清楚设置是否有效
