### ISSUE TITLE
bing报错：CAPTCHA

### ISSUE THREAD

**Issue by cloudaae** [bincooo/chatgpt-adapter#61]
从昨天开始，bing和bing-online都开始报这个错：
{"error":{"message":"[edge-api::resolve] User needs to solve CAPTCHA to continue."}}
请问有办法解决吗？

**Comment by bincooo** [comment]
手动在页面过一次验证，隔天观察一下会不会重复出现

现在怎么又出这个验证了，。

**Comment by leioukupo** [comment]
> 手动在页面过一次验证，隔天观察一下会不会重复出现
> 
> 现在怎么又出这个验证了，。

我网页过了一次，能对话，但是api还是提示CAPTCHA

> 手动在页面过一次验证，隔天观察一下会不会重复出现
> 
> 现在怎么又出这个验证了，。

我网页过了一次，能对话，但是api还是提示CAPTCHA

**Comment by bincooo** [comment]
哦，忘了说。出现CAPTCHA的话需要复制完整的cookies，不能只使用_u了

**Comment by leioukupo** [comment]
> 哦，忘了说。出现CAPTCHA的话需要复制完整的cookies，不能只使用_u了

我用的cookie editor，我需要复制哪项值？
![image](https://github.com/user-attachments/assets/1b4b5bf0-8f1e-4135-a48c-3e0ab7a3eb1c)

**Comment by bincooo** [comment]
全部

**Comment by leioukupo** [comment]
> 全部

我用json格式填写到yaml文件里，运行报错，能否给个填写案例

**Comment by bincooo** [comment]
<img width="338" alt="Screenshot 2024-07-31 at 18 03 50" src="https://github.com/user-attachments/assets/dd511897-540c-4319-bf61-6dddd7cb9dab">

**Comment by leioukupo** [comment]
> <img alt="Screenshot 2024-07-31 at 18 03 50" width="338" src="https://private-user-images.githubusercontent.com/36452456/353788644-dd511897-540c-4319-bf61-6dddd7cb9dab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NzU3MTgsIm5iZiI6MTcyMjQ3NTQxOCwicGF0aCI6Ii8zNjQ1MjQ1Ni8zNTM3ODg2NDQtZGQ1MTE4OTctNTQwYy00MzE5LWJmNjEtNmRkZGQ3Y2I5ZGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAxMjMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZjdmYmU2YzgwMjMwZWEzNmVhOTg3ZWQ0MGQ5YmVhMWFmODU1NzAzNTM4NDFjZTdjOGJjNmFlZGZjNzdmY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ldsOmA8pMI3G1qj1xuLIV9vR_vaAZHXmU6xQR5IT3A">

还是出现CAPTCHA

**Comment by reccea** [comment]
这两天好像频繁出现这个提示

**Comment by bincooo** [comment]
https://github.com/bincooo/chatgpt-adapter/issues/79
