### ISSUE TITLE
是否有支持embedding模型的计划

### ISSUE THREAD

**Issue by yinghuo302** [bincooo/chatgpt-adapter#62]
[aichat](https://github.com/sigoden/aichat)现在已经支持RAG了，效果还可以。所以想问一下有支持embedding模型的计划吗。我也看到一个项目[gemini-to-openai-proxy](https://github.com/cheahjs/gemini-to-openai-proxy)（没试过能不能用），但只支持gemini的Embedding模型，可以集成进去吗。

**Comment by bincooo** [comment]
没有计划。
本项目开发目的更多的是AI逆向工程，而非做api转发。
