### ISSUE TITLE
windows下怎样运行

### ISSUE THREAD

**Issue by windaddyC** [bincooo/chatgpt-adapter#67]
你好，有更多的文档可以给我参考吗？我运行不起来。谢谢。

**Comment by bincooo** [comment]
到右侧的releases下载最新版本的Archive.zip，解压。
复制config.yaml 到window目录下使用命令行`cmd.exe`启动即可
```bash
./server --port 8080
```

**Comment by windaddyC** [comment]
谢谢你。
