### ISSUE TITLE
v2版本可以支持调试bot的接口吗？

### ISSUE THREAD

**Issue by weikecloud** [bincooo/chatgpt-adapter#7]
这个接口：https://www.coze.com/api/draftbot/execute

**Comment by bincooo** [comment]
没有走这个接口，这个调试接口和正常对话接口有什么不同的效果吗？

**Comment by weikecloud** [comment]
这个接口可以微调机器人的详细参数，比如system，Temperature

**Comment by bincooo** [comment]
这个接口已经被字节关闭了吧，我没有找到

**Comment by weikecloud** [comment]
![image](https://github.com/bincooo/chatgpt-adapter/assets/36788191/c68edf3b-b68a-4b1b-a448-c996b9c685da)
https://www.coze.com/api/conversation/chat

**Comment by weikecloud** [comment]
https://www.coze.com/api/draftbot/update 这个接口好像是更新bot的参数

**Comment by bincooo** [comment]
这个 `api/draftbot/update` 接口是全局更新， 无法做到接口隔离意义不大。
这个项目只对接聊天功能，不提供操作coze后台
