### ISSUE TITLE
cohere多了个安全参数设定

### ISSUE THREAD

**Issue by normana234** [bincooo/chatgpt-adapter#72]
官网链接: https://docs.cohere.com/docs/safety-modes
可能考虑在config.yaml加一个和gemini一样的参数配置

**Comment by normana234** [comment]
@normana234 补充，是和两个新模型一起出的，
command-r-08-2024, command-r-plus-08-2024

**Comment by bincooo** [comment]
已更新

**Comment by normana234** [comment]
@bincooo 新模型信息已显示，但点击发送消息报错"不支持该模型"。
![1020](https://github.com/user-attachments/assets/5dd1926c-6436-4fdf-aee9-5a4b8238c03a)
相同密钥在oneapi测试正常，排除密钥原因。

**Comment by normana234** [comment]
@bincooo ok，正常了

**Comment by bincooo** [comment]
好的
