### ISSUE TITLE
3.0-beta 版 bing 报错

### ISSUE THREAD

**Issue by denniszlei** [bincooo/chatgpt-adapter#79]
成功部署3.0-beta，尝试了blackbox, cursor, lmsys，都很好，但是bing无法使用，一直报错 "websocket: close 1000 (normal)"。

vps环境：美国IP，套warp和裸连都试过；
accessToken：抓取header里面的Authrization: Bearer XXXXXX;
本地挂代理访问copilot.microsoft.com正常，chat正常；

具体报错如下：
```json
{
    "error": {
        "message": "websocket: close 1000 (normal)"
    }
}
```

docker的log 如下：
```
2024-12-11 06:37:22 <chatgpt-adapter/core> gin/initializer.go:76 | [INFO] ------ START REQUEST 3a9bfe37-1a3f-44e8-8317-d2df9cf7c96d ---------
[GIN] 2024/12/11 - 06:37:53 | 500 | 30.364463329s |  192.168.XXX.XXX | POST     "/v1/chat/completions"
POST /v1/chat/completions HTTP/1.1
Host: 10.0.XXX.XXX:18085

Accept: */*
Accept-Encoding: gzip, deflate, br
Authorization: eyXXXXXXXX
Connection: keep-alive
Content-Length: 121
Content-Type: application/json
Postman-Token: c895afe3-b619-48ee-85f2-f46b85f9fde0
User-Agent: PostmanRuntime/7.42.0
2024-12-11 06:37:23 <chatgpt-adapter/relay/llm> bing/message.go:59 | [INFO] waitResponse ...
2024-12-11 06:37:53 <chatgpt-adapter/relay/llm> bing/message.go:153 | [ERRO] websocket: close 1000 (normal)
2024-12-11 06:37:53 <chatgpt-adapter/core> gin/initializer.go:83 | [INFO] ------ END REQUEST 3a9bfe37-1a3f-44e8-8317-d2df9cf7c96d ---------
```
分别截图如下：
![Snipaste_2024-12-11_14-43-56](https://github.com/user-attachments/assets/16456992-c021-4ade-83d8-7e708ea8d0c6)
![Snipaste_2024-12-11_14-46-31](https://github.com/user-attachments/assets/b6490453-25c5-49a4-a648-26dcd0d70b3a)

**Comment by bincooo** [comment]
复现了，应该是加了验证

**Comment by reccea** [comment]
这个问题有解决办法吗？

**Comment by bincooo** [comment]
已更新，欢迎测验

**Comment by reccea** [comment]
> 已更新，欢迎测验

docker能不能升级到3.0版？

**Comment by bincooo** [comment]
只有latest

建议自行构建，`deploy`目录有提供`Dockerfile`文件

**Comment by reccea** [comment]
> 只有latest
> 
> 建议自行构建，`deploy`目录有提供`Dockerfile`文件

在bing或copilot登陆后F12网络面板处 没找到/common/oauth2/v2.0/token
倒是找到 wss://copilot.microsoft.com/c/api/chat?api-version=2&accessToken=eyxxxxxx
用这里面的accessToken做为${authorization}后提示：{"error":{"message":"refresh token is unauthorized"}}
请问要怎么解决？

**Comment by bincooo** [comment]
试试脚本获取：
```js
let token = '';
for (var i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (token == '' && key.includes('login.windows.net-accesstoken')) {
    	const obj = JSON.parse(localStorage.getItem(key));
    	token += obj.clientId + '|' + obj.target.split('/')[0];
    }
    if (token != '' && key.includes('login.windows.net-refreshtoken')) {
    	const obj = JSON.parse(localStorage.getItem(key));
    	token += '|' + obj.secret;
    }
}
console.log('token:', token);
```

**Comment by denniszlei** [comment]
试了一下，还是不行，有两个问题：
1. 控制台脚本运行后，拿到的第二个字段Scope是`User.Read openid profile email`且第三串字段refreshtoken没抓到（可能是我的问题）。仔细观察，在 应用程序->本地存储 下面有两个几乎一样的key value对，前一串是貌似正确的scope id，后一个scope就是错误的`User.Read openid profile email`，手动复制正确的scope，并修改token内容，实际得到的最终token为`14638111-XXXX-XXXX-XXXX-XXXXXXXX|140XXXXX-4XXX-4XXX-bXXX-3eXXXXXXXX|M.C560_BL2.0.U.-XXXXXX省略一大串`，可以考虑网页脚本是否需要优化一下？
![image](https://github.com/user-attachments/assets/d24dbbce-7446-4254-ae4a-b44ab08a9f86)

2. 构造完整url的回复还是`401 Unauthorized`，截图如下：
![image](https://github.com/user-attachments/assets/4092b3b1-0981-4fa7-ac4d-4005f596a2ef)

docker log截图如下：
![image](https://github.com/user-attachments/assets/c09236b9-0e2d-442c-8d95-4f00062c472e)


PS, 本地浏览器访问copilot.microsoft.com抓取token的时候用的是机场的ip，docker运行chatgpt-adapter用的是另外的vps，两个IP肯定不同，不晓得有没有影响，供参考。

**Comment by bincooo** [comment]
```js
let token = '';
for (var i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (token == '' && key.includes('login.windows.net-accesstoken') && key.includes('chatai.readwrite')) {
    	const obj = JSON.parse(localStorage.getItem(key));
    	token += obj.clientId + '|' + obj.target.split('/')[0];
    }
}
for (var i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (token != '' && key.includes('login.windows.net-refreshtoken')) {
    	const obj = JSON.parse(localStorage.getItem(key));
    	token += '|' + obj.secret;
    }
}
console.log('token:', token);
```

**Comment by bincooo** [comment]
这是huggingface上部署的，你可以先到这里试试：https://huggingface.co/spaces/wIK5Ez2o/DEMO/blob/main/Dockerfile

**Comment by denniszlei** [comment]
用你部署在huggingface上的服务没问题，棒~！

可能是因为我在甲骨文的arm上部署自己的docker镜像，发现chrome没有arm版就省略了`# Install google`和`# 下载过盾文件` 两个步骤，直接运行的server-arm64，晚点找个x86试试，感谢。

**Comment by reccea** [comment]
> ```js
> let token = '';
> for (var i = 0; i < localStorage.length; i++) {
>     const key = localStorage.key(i);
>     if (token == '' && key.includes('login.windows.net-accesstoken') && key.includes('chatai.readwrite')) {
>     	const obj = JSON.parse(localStorage.getItem(key));
>     	token += obj.clientId + '|' + obj.target.split('/')[0];
>     }
> }
> for (var i = 0; i < localStorage.length; i++) {
>     const key = localStorage.key(i);
>     if (token != '' && key.includes('login.windows.net-refreshtoken')) {
>     	const obj = JSON.parse(localStorage.getItem(key));
>     	token += '|' + obj.secret;
>     }
> }
> console.log('token:', token);
> ```

用这个取到的token，M.Cxxxxxx ，用了这个值，还是提示： {"error":{"message":"refresh token is unauthorized"}} 
这样还不对吗？

**Comment by bincooo** [comment]
> > ```js
> > let token = '';
> > for (var i = 0; i < localStorage.length; i++) {
> >     const key = localStorage.key(i);
> >     if (token == '' && key.includes('login.windows.net-accesstoken') && key.includes('chatai.readwrite')) {
> >     	const obj = JSON.parse(localStorage.getItem(key));
> >     	token += obj.clientId + '|' + obj.target.split('/')[0];
> >     }
> > }
> > for (var i = 0; i < localStorage.length; i++) {
> >     const key = localStorage.key(i);
> >     if (token != '' && key.includes('login.windows.net-refreshtoken')) {
> >     	const obj = JSON.parse(localStorage.getItem(key));
> >     	token += '|' + obj.secret;
> >     }
> > }
> > console.log('token:', token);
> > ```
> 
> 用这个取到的token，M.Cxxxxxx ，用了这个值，还是提示： {"error":{"message":"refresh token is unauthorized"}} 这样还不对吗？

你的账号是pro嘛？不是的话介意发给我排查一下

**Comment by reccea** [comment]
> > > ```js
> > > let token = '';
> > > for (var i = 0; i < localStorage.length; i++) {
> > >     const key = localStorage.key(i);
> > >     if (token == '' && key.includes('login.windows.net-accesstoken') && key.includes('chatai.readwrite')) {
> > >     	const obj = JSON.parse(localStorage.getItem(key));
> > >     	token += obj.clientId + '|' + obj.target.split('/')[0];
> > >     }
> > > }
> > > for (var i = 0; i < localStorage.length; i++) {
> > >     const key = localStorage.key(i);
> > >     if (token != '' && key.includes('login.windows.net-refreshtoken')) {
> > >     	const obj = JSON.parse(localStorage.getItem(key));
> > >     	token += '|' + obj.secret;
> > >     }
> > > }
> > > console.log('token:', token);
> > > ```
> > 
> > 
> > 用这个取到的token，M.Cxxxxxx ，用了这个值，还是提示： {"error":{"message":"refresh token is unauthorized"}} 这样还不对吗？
> 
> 你的账号是pro嘛？不是的话介意发给我排查一下
> 
> 你是不是没传对地方，这个错误只在格式检查的时候会出现： <img alt="Screenshot 2024-12-30 at 19 11 52" width="713" src="https://private-user-images.githubusercontent.com/36452456/399279183-7a02731a-7d06-49a5-ba4b-c2761e223a21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzM0NjUsIm5iZiI6MTczNTU3MzE2NSwicGF0aCI6Ii8zNjQ1MjQ1Ni8zOTkyNzkxODMtN2EwMjczMWEtN2QwNi00OWE1LWJhNGItYzI3NjFlMjIzYTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE1MzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MmQ0YmYyMjM3NDc5OTZjOTI0OThkNTBhZGQ2Y2MwZjkyNGU4N2MyOGFhMTBhZTFhZjg5OWQzZjgzZWU3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5WcNYYdXOWvyPci12ujOKcH_0lB1g6s2RGmtzqtg05I">
> 
> 你看看是否在 `Authorization`请求头正确传入？ <img alt="Screenshot 2024-12-30 at 19 12 48" width="537" src="https://private-user-images.githubusercontent.com/36452456/399279321-d4aecc68-73c8-4e69-a792-5b2aea71727f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzM0NjUsIm5iZiI6MTczNTU3MzE2NSwicGF0aCI6Ii8zNjQ1MjQ1Ni8zOTkyNzkzMjEtZDRhZWNjNjgtNzNjOC00ZTY5LWE3OTItNWIyYWVhNzE3MjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE1MzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZGU3MmI2ZGMwYzllZTM3MzNjOGEyNzg2YmMwZmNmYTVmYjRjODdkOTFhNGRjZTdiMWEyOWI3ZTVjYTM4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.39p5_6EBuSDoC9VWsWHXIJZ4RGckqBtSlMfX92yUroI">

我知道原因了，你那个js取到的结果是：client_id | scope_id | refresh_token
我之前是把client_id | scope_id | 删除，只留了refresh_token当作${authorization}，所以报那个错。如果把client_id | scope_id | refresh_token整个字符串当作${authorization}，就可以正常运行。

**Comment by reccea** [comment]
> > > ```js
> > > let token = '';
> > > for (var i = 0; i < localStorage.length; i++) {
> > >     const key = localStorage.key(i);
> > >     if (token == '' && key.includes('login.windows.net-accesstoken') && key.includes('chatai.readwrite')) {
> > >     	const obj = JSON.parse(localStorage.getItem(key));
> > >     	token += obj.clientId + '|' + obj.target.split('/')[0];
> > >     }
> > > }
> > > for (var i = 0; i < localStorage.length; i++) {
> > >     const key = localStorage.key(i);
> > >     if (token != '' && key.includes('login.windows.net-refreshtoken')) {
> > >     	const obj = JSON.parse(localStorage.getItem(key));
> > >     	token += '|' + obj.secret;
> > >     }
> > > }
> > > console.log('token:', token);
> > > ```
> > 
> > 
> > 用这个取到的token，M.Cxxxxxx ，用了这个值，还是提示： {"error":{"message":"refresh token is unauthorized"}} 这样还不对吗？
> 
> 你的账号是pro嘛？不是的话介意发给我排查一下
> 
> 你是不是没传对地方，这个错误只在格式检查的时候会出现： <img alt="Screenshot 2024-12-30 at 19 11 52" width="713" src="https://private-user-images.githubusercontent.com/36452456/399279183-7a02731a-7d06-49a5-ba4b-c2761e223a21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzM0NjUsIm5iZiI6MTczNTU3MzE2NSwicGF0aCI6Ii8zNjQ1MjQ1Ni8zOTkyNzkxODMtN2EwMjczMWEtN2QwNi00OWE1LWJhNGItYzI3NjFlMjIzYTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE1MzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MmQ0YmYyMjM3NDc5OTZjOTI0OThkNTBhZGQ2Y2MwZjkyNGU4N2MyOGFhMTBhZTFhZjg5OWQzZjgzZWU3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5WcNYYdXOWvyPci12ujOKcH_0lB1g6s2RGmtzqtg05I">
> 
> 你看看是否在 `Authorization`请求头正确传入？ <img alt="Screenshot 2024-12-30 at 19 12 48" width="537" src="https://private-user-images.githubusercontent.com/36452456/399279321-d4aecc68-73c8-4e69-a792-5b2aea71727f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzM0NjUsIm5iZiI6MTczNTU3MzE2NSwicGF0aCI6Ii8zNjQ1MjQ1Ni8zOTkyNzkzMjEtZDRhZWNjNjgtNzNjOC00ZTY5LWE3OTItNWIyYWVhNzE3MjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE1MzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZGU3MmI2ZGMwYzllZTM3MzNjOGEyNzg2YmMwZmNmYTVmYjRjODdkOTFhNGRjZTdiMWEyOWI3ZTVjYTM4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.39p5_6EBuSDoC9VWsWHXIJZ4RGckqBtSlMfX92yUroI">


再请教一个问题，3.0版的bing是不是不能像之前那样有bing、bing-online、bing-vision三个版本？如果需要搜索功能的bing-online要怎么配置？

**Comment by bincooo** [comment]
> > > > ```js
> > > > let token = '';
> > > > for (var i = 0; i < localStorage.length; i++) {
> > > >     const key = localStorage.key(i);
> > > >     if (token == '' && key.includes('login.windows.net-accesstoken') && key.includes('chatai.readwrite')) {
> > > >     	const obj = JSON.parse(localStorage.getItem(key));
> > > >     	token += obj.clientId + '|' + obj.target.split('/')[0];
> > > >     }
> > > > }
> > > > for (var i = 0; i < localStorage.length; i++) {
> > > >     const key = localStorage.key(i);
> > > >     if (token != '' && key.includes('login.windows.net-refreshtoken')) {
> > > >     	const obj = JSON.parse(localStorage.getItem(key));
> > > >     	token += '|' + obj.secret;
> > > >     }
> > > > }
> > > > console.log('token:', token);
> > > > ```
> > > 
> > > 
> > > 用这个取到的token，M.Cxxxxxx ，用了这个值，还是提示： {"error":{"message":"refresh token is unauthorized"}} 这样还不对吗？
> > 
> > 
> > 你的账号是pro嘛？不是的话介意发给我排查一下
> > 你是不是没传对地方，这个错误只在格式检查的时候会出现： <img alt="Screenshot 2024-12-30 at 19 11 52" width="713" src="https://private-user-images.githubusercontent.com/36452456/399279183-7a02731a-7d06-49a5-ba4b-c2761e223a21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzM0NjUsIm5iZiI6MTczNTU3MzE2NSwicGF0aCI6Ii8zNjQ1MjQ1Ni8zOTkyNzkxODMtN2EwMjczMWEtN2QwNi00OWE1LWJhNGItYzI3NjFlMjIzYTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE1MzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MmQ0YmYyMjM3NDc5OTZjOTI0OThkNTBhZGQ2Y2MwZjkyNGU4N2MyOGFhMTBhZTFhZjg5OWQzZjgzZWU3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5WcNYYdXOWvyPci12ujOKcH_0lB1g6s2RGmtzqtg05I">
> > 你看看是否在 `Authorization`请求头正确传入？ <img alt="Screenshot 2024-12-30 at 19 12 48" width="537" src="https://private-user-images.githubusercontent.com/36452456/399279321-d4aecc68-73c8-4e69-a792-5b2aea71727f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzM0NjUsIm5iZiI6MTczNTU3MzE2NSwicGF0aCI6Ii8zNjQ1MjQ1Ni8zOTkyNzkzMjEtZDRhZWNjNjgtNzNjOC00ZTY5LWE3OTItNWIyYWVhNzE3MjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE1MzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZGU3MmI2ZGMwYzllZTM3MzNjOGEyNzg2YmMwZmNmYTVmYjRjODdkOTFhNGRjZTdiMWEyOWI3ZTVjYTM4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.39p5_6EBuSDoC9VWsWHXIJZ4RGckqBtSlMfX92yUroI">
> 
> 再请教一个问题，3.0版的bing是不是不能像之前那样有bing、bing-online、bing-vision三个版本？如果需要搜索功能的bing-online要怎么配置？

只有 bing 一个
