### ISSUE TITLE
3.0-beta windsurf 4o没问题，Claude报错

### ISSUE THREAD

**Issue by kbykb** [bincooo/chatgpt-adapter#80]
![dc914f1eb4f9bf40f903b139036e6bbd](https://github.com/user-attachments/assets/c33c5315-ae8b-4818-b476-755b38d9af7f)
![caf6c0f25a1d139c9687be85f6a2034](https://github.com/user-attachments/assets/63e441fe-8f94-4e28-bf68-5566d9dd2e1a)

如图，4o正常，但是Claude就会报错，直接curl、sillytavern使用皆是如此
（话说这次为啥不内置到config里而是要自己curl了）

**Comment by bincooo** [comment]
这个是周期性的免费不限，所以传key更方便

**Comment by kbykb** [comment]
> 这个是周期性的免费不限，所以传key更方便

谢谢大佬回复！不过对酒馆来说，单次输出楼层太高（比如在两三百楼的卡里发一条消息）会直接触发rpm限制，感觉还是有个轮询方便些

**Comment by bincooo** [comment]
我一搬挂到oneapi上用的，除了短次数才自己搞轮训

**Comment by kbykb** [comment]
> 我一般挂到oneapi上用的，除了短次数才自己搞轮训

2024-12-23 06:48:22 <chatgpt-adapter/core> gin/v1.go:47 | [INFO] curr model: windsurf/claude-3-5-sonnet
[2Kwinbin  | 2024-12-23 06:48:24 <chatgpt-adapter/relay/llm> windsurf/message.go:144 | [INFO] waitResponse ...
[2Kwinbin  | 2024-12-23 06:48:24 <chatgpt-adapter/core> gin/initializer.go:84 | [INFO] ------ END REQUEST 4c01ed45-7233-4069-a3e4-e30b4eaa80b8 ---------
[2Kwinbin  | [GIN] 2024/12/23 - 06:48:24 | 500 |  2.554363764s |    154.12.80.80 | POST     "/v1/chat/completions"
佬，重新编译了，还是空回复55555

**Comment by bincooo** [comment]
```yaml
specialized: true
```

合并上下文试试

**Comment by kbykb** [comment]
> ```yaml
> specialized: true
> ```
> 
> 合并上下文试试

谢谢佬回复，话说我能问下这个设置在哪里吗（

**Comment by bincooo** [comment]
<img width="485" alt="Screenshot 2024-12-23 at 17 44 44" src="https://github.com/user-attachments/assets/d2374268-0f2a-48de-a33d-1fd2e3d82856" />

config.yaml

**Comment by kbykb** [comment]
> <img alt="Screenshot 2024-12-23 at 17 44 44" width="485" src="https://private-user-images.githubusercontent.com/36452456/398121766-d2374268-0f2a-48de-a33d-1fd2e3d82856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDczOTksIm5iZiI6MTczNDk0NzA5OSwicGF0aCI6Ii8zNjQ1MjQ1Ni8zOTgxMjE3NjYtZDIzNzQyNjgtMGYyYS00OGRlLWEzM2QtMWZkMmUzZDgyODU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA5NDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYzgwNzg4Y2MyZjY3NGNkNTAwNjEyZDExOGM3MzU3ZmZlODRiOWEyNWVmNTEyMmU0NWM4NmNjZWM2YzlhMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XioHYeIRGyjOfVtoc5AXaA9OQ3onxazClVKl3ZGZytM">
> config.yaml

谢谢谢谢！用上了！

**Comment by kbykb** [comment]
佬- -你是不是把wind的uuid硬编码了，我测试了完全不需要密钥连上就是用

**Comment by bincooo** [comment]
没有啊，不应该。你确定关闭了么

**Comment by kbykb** [comment]
> 没有啊，不应该。你确定关闭了么

我怕是我vps有啥记忆，本地也开了一个酒馆测试，确实啥密钥也不填，填上api直接就是用

**Comment by kbykb** [comment]
> 没有啊，不应该。你确定关闭了么

还是说我曾经用一个uuid连上过，所以服务器会记录？下次请求那个地址直接复用了？

**Comment by bincooo** [comment]
我这不行，会报 [unauthenticated] invalid api key

**Comment by bincooo** [comment]
哦，这有可能。大概知道怎么一回事了

**Comment by kbykb** [comment]
> 哦，这有可能。大概知道怎么一回事了

佬，你在使用的时候有没有遇到一个奇怪的问题，比如我在5楼发问，但ai在6楼继续回到我3楼的问题，好像看不到我的5楼一样，windsurf

**Comment by bincooo** [comment]
<img width="860" alt="Screenshot 2024-12-27 at 09 28 18" src="https://github.com/user-attachments/assets/72b3576f-5041-4674-bb22-5d28b2bd83dc" />
ai出幻觉了吧
