### ISSUE TITLE
有没有好心人解惑一下

### ISSUE THREAD

**Issue by luoxiashen** [bincooo/chatgpt-adapter#81]
OpenAIClientException({
  "uri": "http://ip:7860/v1/chat/completions",
  "method": "POST",
  "code": 500,
  "message": "Unsuccessful response",
  "body": {
    "error": {
      "message": "[internal] internal error"
    }
  }
})

```#0      OpenAIClient.makeRequestStream (package:openai_dart/src/generated/client.dart:301)
<asynchronous suspension>
#1      OpenAIClient.createChatCompletionStream (package:openai_dart/src/client.dart:97)
<asynchronous suspension>
#2      _onCreateText.<anonymous closure> (package:gpt_box/view/page/home/req.dart:236)
<asynchronous suspension>
```

为什么会报这个错啊，我的参数应该没问题。我把本地代理关了，因为不关也会报错，我也不知道怎么设置。模型能正常刷新出来，但是一问就报这个错误。

**Comment by luoxiashen** [comment]
2024-12-23 03:32:36 <chatgpt-adapter/core> gin/v1.go:47 | [INFO] curr model: cursor/gpt-4o-mini
2024-12-23 03:32:36 <chatgpt-adapter/core> gin/initializer.go:77 | [INFO] ------ START REQUEST df26f3e1-0f0e-4e99-ac7f-ffe3f131b182 ---------
POST /v1/chat/completions HTTP/1.1
Host: 74.48.204.226:7860
Accept: application/json
Accept-Encoding: gzip
Authorization: Bearer user_01JFRPTM3WBKDM9RXDNVB8SC8Z%3A%3AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhdXRoMHx1c2VyXzAxSkZSUFRNM1dCS0RNOVJYRE5WQjhTQzhaIiwidGltZSI6IjE3MzQ5MjIzMjIiLCJyYW5kb21uZXNzIjoiYzJlNDdkYTEtMjM4ZS00OGRjIiwiZXhwIjo0MzI2OTIyMzIyLCJpc3MiOiJodHRwczovL2F1dGhlbnRpY2F0aW9uLmN1cnNvci5zaCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MiLCJhdWQiOiJodHRwczovL2N1cnNvci5jb20ifQ.Dt07_XpaCayFQWe2bcoqn6-6eQdl-1s4II8L_2Kzxv0
Content-Length: 674
Content-Type: application/json
Openai-Beta: assistants=v2
User-Agent: Dart/3.5 (dart:io)


2024-12-23 03:32:36 <chatgpt-adapter/core> gin/v1.go:47 | [INFO] curr model: cursor/gpt-4o-mini
2024-12-23 03:32:36 <chatgpt-adapter/relay/llm> cursor/message.go:105 | [INFO] waitResponse ...
2024-12-23 03:32:36 <chatgpt-adapter/relay/llm> cursor/message.go:146 | [ERRO] [internal] internal error
2024-12-23 03:32:36 <chatgpt-adapter/core> gin/initializer.go:84 | [INFO] ------ END REQUEST 3e46d718-5e91-48ae-ba7a-00d033e796c4 ---------
[GIN] 2024/12/23 - 03:32:36 | 500 |  239.853627ms | 123.147.245.140 | POST     "/v1/chat/completions"
2024-12-23 03:32:36 <chatgpt-adapter/relay/llm> cursor/message.go:105 | [INFO] waitResponse ...
2024-12-23 03:32:36 <chatgpt-adapter/relay/llm> cursor/message.go:146 | [ERRO] [internal] internal error
2024-12-23 03:32:36 <chatgpt-adapter/core> gin/initializer.go:84 | [INFO] ------ END REQUEST df26f3e1-0f0e-4e99-ac7f-ffe3f131b182 ---------
[GIN] 2024/12/23 - 03:32:36 | 500 |  242.912808ms | 123.147.245.140 | POST     "/v1/chat/completions"

**Comment by bincooo** [comment]
没有复现，你这个是最新代码吗？
此外，你的cursor key 暴露了

<img width="877" alt="Screenshot 2024-12-23 at 12 05 13" src="https://github.com/user-attachments/assets/cc249144-7764-4354-b5da-9b8ec0f954b5" />

**Comment by luoxiashen** [comment]
> 没有复现，你这个是最新代码吗？
> 此外，你的cursor key 暴露了
> 
> <img width="877" alt="Screenshot 2024-12-23 at 12 05 13" src="https://github.com/user-attachments/assets/cc249144-7764-4354-b5da-9b8ec0f954b5" />
> 

大大你测试一下我的key有没有问题，那个随便注册的暴露没关系

**Comment by bincooo** [comment]
上面用的就是是你的

**Comment by luoxiashen** [comment]
> 上面用的就是是你的

已修，可参考 https://huggingface.co/spaces/wIK5Ez2o/DEMO/blob/main/Dockerfile 部署

我参考的你这个部署的，docker

**Comment by luoxiashen** [comment]
server:
  port: 7860
  
  debug: false

browser-less:
  enabled: true
  port: 2543
  #reversal: http://127.0.0.1:2543
  disabled-gpu: true
  headless: new

specialized: false

matcher:
  - match: I do not engage
    over: ":\n"
    notice:
    regex: |
      "(?i)I do not engage .+:\n":""
  - match: <thinking>
    over: </thinking>
    notice:
    regex: |
      "(?s)<thinking>.+</thinking>":""
      
cursor:
  checksum: 'zo-v9_v2qxRYcau35NDnAHAVxQkLe6IHw8opkpKV4oLyo0PhPeSpj4QTw2VJ20Lngrz7XNTQ/clDRF5FOm3B1uK-mQDyFBRqD8JNj4kLByaAfm4AqK6IMbFYcrqXMMXexubsTRrr1'

这是配置文件，不知道有没有问题

**Comment by bincooo** [comment]
也没问题
<img width="1360" alt="Screenshot 2024-12-23 at 12 19 25" src="https://github.com/user-attachments/assets/3772f3d2-41dd-45fb-8151-a8e4b9544f39" />

你试试：

```curl
curl --request POST \
  --url https://wik5ez2o-demo.hf.space/proxies/v1/chat/completions \
  --header 'Authorization: Bearer user_01JFRPTM3WBKDM9RXDNVB8SC8Z%3A%3AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhdXRoMHx1c2VyXzAxSkZSUFRNM1dCS0RNOVJYRE5WQjhTQzhaIiwidGltZSI6IjE3MzQ5MjIzMjIiLCJyYW5kb21uZXNzIjoiYzJlNDdkYTEtMjM4ZS00OGRjIiwiZXhwIjo0MzI2OTIyMzIyLCJpc3MiOiJodHRwczovL2F1dGhlbnRpY2F0aW9uLmN1cnNvci5zaCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MiLCJhdWQiOiJodHRwczovL2N1cnNvci5jb20ifQ.Dt07_XpaCayFQWe2bcoqn6-6eQdl-1s4II8L_2Kzxv0' \
  --header 'content-type: application/json' \
  --data '{
  "messages": [
    {
      "role": "user",
      "content": "hi"
    },
    {
      "role": "assistant",
      "content": "hi too~"
    },
    {
      "role": "user",
      "content": "who are you?"
    }
  ],
  "model": "cursor/gpt-4o-mini",
  "temperature": 2,
  "frequency_penalty": 0.64,
  "presence_penalty": 0.65,
  "top_p": 1,
  "max_tokens": 8192,
  "stream": true
}'
```

**Comment by luoxiashen** [comment]
> 也没问题
> <img width="1360" alt="Screenshot 2024-12-23 at 12 19 25" src="https://github.com/user-attachments/assets/3772f3d2-41dd-45fb-8151-a8e4b9544f39" />
> 
> 你试试,这是hf的demo：
> 
> ```curl
> curl --request POST \
>   --url https://wik5ez2o-demo.hf.space/proxies/v1/chat/completions \
>   --header 'Authorization: Bearer user_01JFRPTM3WBKDM9RXDNVB8SC8Z%3A%3AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhdXRoMHx1c2VyXzAxSkZSUFRNM1dCS0RNOVJYRE5WQjhTQzhaIiwidGltZSI6IjE3MzQ5MjIzMjIiLCJyYW5kb21uZXNzIjoiYzJlNDdkYTEtMjM4ZS00OGRjIiwiZXhwIjo0MzI2OTIyMzIyLCJpc3MiOiJodHRwczovL2F1dGhlbnRpY2F0aW9uLmN1cnNvci5zaCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MiLCJhdWQiOiJodHRwczovL2N1cnNvci5jb20ifQ.Dt07_XpaCayFQWe2bcoqn6-6eQdl-1s4II8L_2Kzxv0' \
>   --header 'content-type: application/json' \
>   --data '{
>   "messages": [
>     {
>       "role": "user",
>       "content": "hi"
>     },
>     {
>       "role": "assistant",
>       "content": "hi too~"
>     },
>     {
>       "role": "user",
>       "content": "who are you?"
>     }
>   ],
>   "model": "cursor/gpt-4o-mini",
>   "temperature": 2,
>   "frequency_penalty": 0.64,
>   "presence_penalty": 0.65,
>   "top_p": 1,
>   "max_tokens": 8192,
>   "stream": true
> }'
> ```



我用的这个软件https://res.lolli.tech/serverbox/pkg/ServerBox_1120_arm64.apk。![IMG_20241223_123434.jpg](https://github.com/user-attachments/assets/f42452b0-7962-4613-a473-9f74713287aa)
配置置如图，你看能不能复现呢

**Comment by luoxiashen** [comment]
我是国外的服务器，难道这跟IP有关系吗

**Comment by normana234** [comment]
> 没有复现，你这个是最新代码吗？ 此外，你的cursor key 暴露了
> 
> <img alt="Screenshot 2024-12-23 at 12 05 13" width="877" src="https://private-user-images.githubusercontent.com/36452456/398049072-cc249144-7764-4354-b5da-9b8ec0f954b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MzI0MjAsIm5iZiI6MTczNDkzMjEyMCwicGF0aCI6Ii8zNjQ1MjQ1Ni8zOTgwNDkwNzItY2MyNDkxNDQtNzc2NC00MzU0LWI1ZGEtOWI4ZWMwZjk1NGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA1MzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDM2ZTI5NDkyMWUwNmViZGZiYzVmNWY5N2YxNjZlYjMwNDFiY2ZiZDg1NjJkYjcwNmIzYjI4NzM1ZDdlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._RQxunpVuKcJsH783DmV6_MQ_Pm037CZjodpzoDeucU">

问一下，图里这个工具是什么，想了解下。

**Comment by bincooo** [comment]
Hoppscotch

**Comment by normana234** [comment]
> Hoppscotch

好的，谢谢
