### ISSUE TITLE
lmsys和blockbox报错

### ISSUE THREAD

**Issue by normana234** [bincooo/chatgpt-adapter#82]
已经更新到最新版(截图时间)，报错如下
blockbox
![blockbox error](https://github.com/user-attachments/assets/4742085b-17aa-4a62-a00f-0ed71a7d755a)
lmsys
![lmsys error](https://github.com/user-attachments/assets/0aefdcab-5360-4119-84b9-8ef75bd9a182)

**Comment by bincooo** [comment]
README.md里有写，你需要配置config.yaml文件：
https://bincooo.github.io/chatgpt-adapter/#/blackbox

**Comment by normana234** [comment]
> README.md里有写，你需要配置config.yaml文件： https://bincooo.github.io/chatgpt-adapter/#/blackbox

确实，配置文件格式变了，我的错，lmsys呢？

**Comment by bincooo** [comment]
一样

**Comment by normana234** [comment]
> 一样

尴尬了，抱歉，打扰了。
