### ISSUE TITLE
功能请求：可以有docker版本吗

### ISSUE THREAD

**Issue by QingyeSC** [bincooo/chatgpt-adapter#84]
新手摸索了半天，终于弄好来了go和编译，但是发现关闭终端，项目就没了，想问一下佬计划出docker版本吗，好用且方便更新

**Comment by bincooo** [comment]
你可以在此处获取latest版本：https://github.com/bincooo/chatgpt-adapter/pkgs/container/chatgpt-adapter/328215665?tag=latest

**Comment by QingyeSC** [comment]
![image](https://github.com/user-attachments/assets/b9d53c76-090f-4d41-9604-a72986913ffe)
佬，启动是这样的

**Comment by QingyeSC** [comment]
我自己弄镜像的时候也遇到这个问题

**Comment by bincooo** [comment]
关闭浏览器自动化
```yaml
browser-less:
  enabled: false
```
或者自行构建Dockerfile-BL版本
