### ISSUE TITLE
看到代码有tokens计算返回的实现，但是似乎有个bug?prompt_tokens"部分一直为0

### ISSUE THREAD

**Issue by QingyeSC** [bincooo/chatgpt-adapter#85]
![image](https://github.com/user-attachments/assets/7db74452-dacc-4962-9158-2104fbb002a3)
佬你看看，我在测试的时候发现winsurf的prompt_tokens":部分是0

**Comment by QingyeSC** [comment]
问了AI，但是对go是一窍不通，有点不敢改了

**Comment by bincooo** [comment]
已处理

**Comment by QingyeSC** [comment]
谢谢佬，确实可用了

**Comment by QingyeSC** [comment]
佬，config.yaml里的思维链正则替换必须要开吗，我有时候想看AI思考过程来着

**Comment by bincooo** [comment]
不必，可以注释

**Comment by QingyeSC** [comment]
感谢！
